const QUOTES = [
  "Hoy también suma.",
  "Tu cuerpo registró tu llegada.",
  "La mejor hora es ahora.",
  "Un minuto cuenta.",
  "Todo movimiento deja huella.",
  "Empezar sigue siendo una gran idea.",
  "Tu energía está en camino.",
  "Ya hiciste algo bueno por vos.",
  "El día mejora desde acá.",
  "Bienvenido a tu momento.",
  "Tu espalda lo celebra.",
  "La postura está agradecida.",
  "Hay músculos despertando.",
  "El movimiento acaba de comenzar.",
  "Tu versión futura sonríe.",
  "El progreso llegó temprano.",
  "Hoy elegiste bien.",
  "El bienestar te estaba esperando.",
  "Hora de invertir en vos.",
  "Acá empieza algo bueno.",
  "El sofá entiende, pero no aprueba.",
  "La gravedad sigue insistiendo.",
  "Tu columna pidió este turno.",
  "Los músculos estaban aburridos.",
  "Tu equilibrio vino a entrenar.",
  "El cuerpo recibió la notificación.",
  "Estado: listo para moverse.",
  "Se detectó una excelente decisión.",
  "El modo bienestar está activo.",
  "Actualización instalada correctamente.",
  "Tu respiración tiene planes.",
  "Hoy hay energía disponible.",
  "Tu centro está despierto.",
  "Un paso más adelante.",
  "Todo suma cuando se repite.",
  "Tu cuerpo recuerda cada esfuerzo.",
  "El cambio ama la constancia.",
  "La práctica está haciendo su trabajo.",
  "No parece mucho, pero cuenta.",
  "Seguir es una habilidad.",
  "El movimiento es una conversación.",
  "Escuchá a tu cuerpo.",
  "El equilibrio se construye.",
  "Tu fuerza está creciendo.",
  "La flexibilidad también es mental.",
  "Hoy entrenás posibilidades.",
  "Cada repetición enseña algo.",
  "Hay progreso en marcha.",
  "El bienestar no tiene prisa.",
  "Todo a su tiempo.",
  "Los grandes cambios son discretos.",
  "Tu mejor hábito te saluda.",
  "Gracias por aparecer.",
  "Viniste. Eso importa.",
  "La disciplina sonríe en silencio.",
  "El esfuerzo tiene memoria.",
  "Todo comienzo vale.",
  "Hoy puede sorprenderte.",
  "El movimiento abre puertas.",
  "La energía sigue a la acción.",
  "Lo importante es volver.",
  "Tu rutina te fortalece.",
  "La constancia tiene superpoderes.",
  "Hoy es una buena oportunidad.",
  "El progreso ya empezó.",
  "Nada cambia hasta que algo cambia.",
  "Tu cuerpo está aprendiendo.",
  "Estás construyendo algo valioso.",
  "Cada día cuenta distinto.",
  "Lo estás haciendo bien.",
  "Tu espalda manda saludos.",
  "Se registró una decisión inteligente.",
  "El reformer te estaba esperando.",
  "Tu postura tiene futuro.",
  "Alerta de autocuidado.",
  "La gravedad encontró competencia.",
  "Tu abdomen tomó nota.",
  "Los hombros agradecen.",
  "Se habilitó el modo fuerte.",
  "Nivel de bienestar: aumentando.",
  "Hay magia en la repetición.",
  "El cambio llega entrenando.",
  "Respirar también cuenta.",
  "Todo progreso fue pequeño primero.",
  "El movimiento es una celebración.",
  "Hoy también es parte del plan.",
  "Tu energía está regresando.",
  "Un hábito más fuerte hoy.",
  "Cada día enseña algo.",
  "La práctica construye confianza.",
  "Tu mejor versión no tiene apuro.",
  "El bienestar es acumulativo.",
  "La paciencia también entrena.",
  "Hoy sembrás resultados.",
  "La acción supera la intención.",
  "Estás más cerca de lo que creés.",
  "Seguir vale mucho.",
  "La constancia hace magia lenta.",
  "Tu cuerpo sabe adaptarse.",
  "Todo empieza apareciendo.",
  "Tu columna aprobó esta decisión.",
  "Los músculos enviaron un agradecimiento.",
  "El sofá presentó una queja formal.",
  "Estado físico: cargando mejoras.",
  "El equilibrio está en línea.",
  "Tu centro tomó el control.",
  "La postura acaba de ganar puntos.",
  "Modo sedentario: pausado.",
  "Tu energía pidió más de esto.",
  "Movimiento detectado. Excelente.",
  "La mejor inversión sos vos.",
  "Tu salud suma intereses.",
  "Hoy construís bienestar.",
  "Todo esfuerzo encuentra destino.",
  "La fuerza llega entrenando.",
  "El equilibrio llega practicando.",
  "Tu cuerpo aprecia la constancia.",
  "Cada sesión deja algo.",
  "Todo movimiento importa.",
  "Bien hecho por estar acá.",
  "Lo difícil era empezar.",
  "El resto viene después.",
  "Tu bienestar tiene prioridad.",
  "Hay valor en cada intento.",
  "Hoy también vale.",
  "Tu cuerpo no olvida.",
  "Todo avance merece respeto.",
  "Estás construyendo confianza.",
  "El progreso no siempre se ve.",
  "Pero siempre trabaja.",
  "Son buenas noticias para tu espalda.",
  "Tu postura está celebrando.",
  "Se encontró motivación en el sistema.",
  "Tu energía fue actualizada.",
  "Vos seguís avanzando.",
  "El movimiento tiene buena reputación.",
  "Hoy elegiste moverte.",
  "Excelente decisión.",
  "Tu bienestar te lo agradece.",
  "Un poco mejor cada día.",
  "El progreso ama la paciencia.",
  "Tu esfuerzo importa.",
  "El cambio ya empezó.",
  "Estás creando algo duradero.",
  "Hoy suma más de lo que parece.",
  "Tu futuro yo está orgulloso.",
  "Seguí así.",
  "Bienvenido de nuevo.",
  "Qué bueno verte por acá.",
  "Hoy también cuenta.",
  "Lo estás haciendo mejor de lo que creés.",
  "Tu yo de mañana te está alentando.",
  "La constancia tiene mejor memoria que la motivación.",
  "Un paso pequeño sigue siendo un paso.",
  "No subestimes el poder de aparecer.",
  "Respirá. Ya estás acá.",
  "El progreso rara vez hace ruido.",
  "Todo gran hábito empezó con un día cualquiera.",
  "Tu cuerpo escucha lo que hacés por él.",
  "La perfección está sobrevalorada.",
  "Las mejores inversiones no siempre están en el banco.",
  "Hacer algo siempre gana a esperar hacerlo perfecto.",
  "El movimiento cambia más cosas de las que parece.",
  "A veces avanzar es simplemente no abandonar.",
  "Hoy puede ser un buen día para sorprenderte.",
  "Tu energía es un recurso renovable: recargala.",
  "Los resultados aman la paciencia.",
  "El bienestar también se entrena.",
  "Gracias por elegirte hoy.",
  "Si llegaste hasta acá, ya hiciste lo más difícil.",
  "Tu columna aprueba esta decisión.",
  "El sofá tenía otros planes para vos.",
  "Cada músculo tiene una historia que contar.",
  "El equilibrio no se encuentra, se practica.",
  "Hay días para romper récords y días para aparecer. Ambos cuentan.",
  "Lo importante no es la velocidad, es la dirección.",
  "Hoy es un excelente día para moverte.",
  "La mejor versión de vos no tiene apuro.",
  "Pequeñas acciones, grandes efectos.",
  "\"Haz lo que puedas, con lo que tengas, donde estés.\" — Theodore Roosevelt",
  "\"La acción es la clave fundamental de todo éxito.\" — Pablo Picasso",
  "\"No cuentes los días, haz que los días cuenten.\" — Muhammad Ali",
  "\"La energía y la persistencia conquistan todas las cosas.\" — Benjamin Franklin",
  "\"La felicidad depende de nosotros mismos.\" — Aristóteles",
  "\"El secreto para salir adelante es comenzar.\" — Mark Twain",
  "\"Todo parece imposible hasta que se hace.\" — Nelson Mandela",
  "\"La disciplina es elegir entre lo que quieres ahora y lo que quieres más.\" — Abraham Lincoln",
  "\"La suerte favorece a quienes se preparan.\" — Louis Pasteur",
  "\"La mejor manera de predecir el futuro es crearlo.\" — Peter Drucker",
  "Hoy tu café tiene competencia.",
  "Tu espalda pidió esto.",
  "La gravedad sigue fuerte. Vos también.",
  "Moverse es una forma de agradecerle al cuerpo.",
  "Si nadie te lo dijo hoy: vas bien.",
  "El cambio suele llegar disfrazado de rutina.",
  "La magia favorita del cuerpo se llama adaptación.",
  "Un poco es infinitamente más que nada.",
  "Seguir cuenta más que empezar.",
  "Bienvenido. Tu bienestar te estaba esperando.",
]

export function getDailyQuote() {
  const today = new Date()
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000
  )
  return QUOTES[dayOfYear % QUOTES.length]
}
